// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_Main
#include <Main.h>
#endif
#ifndef INCLUDED_Packer
#include <Packer.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_Unpacker
#include <Unpacker.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_4_main,"Main","main",0xed0e206e,"Main.main","Main.hx",4,0x087e5c05)
HX_LOCAL_STACK_FRAME(_hx_pos_e47a9afac0942eb9_20_printUsage,"Main","printUsage",0x9a492fa9,"Main.printUsage","Main.hx",20,0x087e5c05)

void Main_obj::__construct() { }

Dynamic Main_obj::__CreateEmpty() { return new Main_obj; }

void *Main_obj::_hx_vtable = 0;

Dynamic Main_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< Main_obj > _hx_result = new Main_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool Main_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x07825a7d;
}

void Main_obj::main(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_4_main)
HXLINE(   5)		::Array< ::String > args = ::Sys_obj::args();
HXLINE(   6)		if ((args->length < 3)) {
HXLINE(   7)			::Main_obj::printUsage();
HXLINE(   8)			::Sys_obj::exit(1);
            		}
HXLINE(  10)		::String _hx_switch_0 = args->__get(0).toLowerCase();
            		if (  (_hx_switch_0==HX_("pack",d9,d6,51,4a)) ){
HXLINE(  12)			::Packer_obj::run(args->__get(1),args->__get(2));
HXDLIN(  12)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("unpack",b2,dd,26,68)) ){
HXLINE(  11)			::Unpacker_obj::run(args->__get(1),args->__get(2));
HXDLIN(  11)			goto _hx_goto_0;
            		}
            		/* default */{
HXLINE(  14)			::Sys_obj::println((HX_("Unknown command: ",7b,3c,44,01) + args->__get(0)));
HXLINE(  15)			::Main_obj::printUsage();
HXLINE(  16)			::Sys_obj::exit(1);
            		}
            		_hx_goto_0:;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Main_obj,main,(void))

void Main_obj::printUsage(){
            	HX_STACKFRAME(&_hx_pos_e47a9afac0942eb9_20_printUsage)
HXLINE(  21)		::Sys_obj::println(HX_("PCF Tool",c5,17,8a,63));
HXLINE(  22)		::Sys_obj::println(HX_("  pcf_tool unpack <input.pcf>    <output_folder>",55,14,09,70));
HXLINE(  23)		::Sys_obj::println(HX_("  pcf_tool pack   <input_folder> <output.pcf>",92,52,e6,22));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(Main_obj,printUsage,(void))


Main_obj::Main_obj()
{
}

bool Main_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"main") ) { outValue = main_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"printUsage") ) { outValue = printUsage_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *Main_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *Main_obj_sStaticStorageInfo = 0;
#endif

::hx::Class Main_obj::__mClass;

static ::String Main_obj_sStaticFields[] = {
	HX_("main",39,38,56,48),
	HX_("printUsage",b4,b1,c1,02),
	::String(null())
};

void Main_obj::__register()
{
	Main_obj _hx_dummy;
	Main_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("Main",59,64,2f,33);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &Main_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(Main_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< Main_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = Main_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = Main_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

