// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_BinReader
#include <BinReader.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_BytesInput
#include <haxe/io/BytesInput.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_haxe_io_Input
#include <haxe/io/Input.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_442cef72209386ca_9_new,"BinReader","new",0x32c40f3c,"BinReader.new","BinReader.hx",9,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_14_readI32,"BinReader","readI32",0xb1585c6e,"BinReader.readI32","BinReader.hx",14,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_15_readU32,"BinReader","readU32",0xb161777a,"BinReader.readU32","BinReader.hx",15,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_16_readBool,"BinReader","readBool",0x7785c244,"BinReader.readBool","BinReader.hx",16,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_17_readBytes,"BinReader","readBytes",0x24242111,"BinReader.readBytes","BinReader.hx",17,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_19_readUtf8,"BinReader","readUtf8",0x8418934b,"BinReader.readUtf8","BinReader.hx",19,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_24_skip,"BinReader","skip",0x3c1bd823,"BinReader.skip","BinReader.hx",24,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_25_pos,"BinReader","pos",0x32c59c70,"BinReader.pos","BinReader.hx",25,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_26_remaining,"BinReader","remaining",0x516692d2,"BinReader.remaining","BinReader.hx",26,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_27_eof,"BinReader","eof",0x32bd4398,"BinReader.eof","BinReader.hx",27,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_31_hexU32,"BinReader","hexU32",0x8c5dd6dd,"BinReader.hexU32","BinReader.hx",31,0xc116abb4)
HX_LOCAL_STACK_FRAME(_hx_pos_442cef72209386ca_36_parseHex,"BinReader","parseHex",0xe4e3b00c,"BinReader.parseHex","BinReader.hx",36,0xc116abb4)

void BinReader_obj::__construct( ::haxe::io::Bytes b){
            	HX_GC_STACKFRAME(&_hx_pos_442cef72209386ca_9_new)
HXLINE(  10)		this->bi =  ::haxe::io::BytesInput_obj::__alloc( HX_CTX ,b,null(),null());
HXLINE(  11)		this->bi->set_bigEndian(false);
            	}

Dynamic BinReader_obj::__CreateEmpty() { return new BinReader_obj; }

void *BinReader_obj::_hx_vtable = 0;

Dynamic BinReader_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< BinReader_obj > _hx_result = new BinReader_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool BinReader_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x595748a6;
}

int BinReader_obj::readI32(){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_14_readI32)
HXDLIN(  14)		return this->bi->readInt32();
            	}


HX_DEFINE_DYNAMIC_FUNC0(BinReader_obj,readI32,return )

int BinReader_obj::readU32(){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_15_readU32)
HXDLIN(  15)		return this->bi->readInt32();
            	}


HX_DEFINE_DYNAMIC_FUNC0(BinReader_obj,readU32,return )

bool BinReader_obj::readBool(){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_16_readBool)
HXDLIN(  16)		return (this->bi->readByte() != 0);
            	}


HX_DEFINE_DYNAMIC_FUNC0(BinReader_obj,readBool,return )

 ::haxe::io::Bytes BinReader_obj::readBytes(int n){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_17_readBytes)
HXDLIN(  17)		return this->bi->read(n);
            	}


HX_DEFINE_DYNAMIC_FUNC1(BinReader_obj,readBytes,return )

::String BinReader_obj::readUtf8(int n){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_19_readUtf8)
HXLINE(  20)		 ::haxe::io::Bytes b = this->bi->read(n);
HXLINE(  21)		return b->getString(0,n,null());
            	}


HX_DEFINE_DYNAMIC_FUNC1(BinReader_obj,readUtf8,return )

void BinReader_obj::skip(int n){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_24_skip)
HXDLIN(  24)		 ::haxe::io::BytesInput fh = this->bi;
HXDLIN(  24)		fh->set_position((fh->pos + n));
            	}


HX_DEFINE_DYNAMIC_FUNC1(BinReader_obj,skip,(void))

int BinReader_obj::pos(){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_25_pos)
HXDLIN(  25)		return this->bi->pos;
            	}


HX_DEFINE_DYNAMIC_FUNC0(BinReader_obj,pos,return )

int BinReader_obj::remaining(){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_26_remaining)
HXDLIN(  26)		return (this->bi->totlen - this->bi->pos);
            	}


HX_DEFINE_DYNAMIC_FUNC0(BinReader_obj,remaining,return )

bool BinReader_obj::eof(){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_27_eof)
HXDLIN(  27)		return (this->bi->pos >= this->bi->totlen);
            	}


HX_DEFINE_DYNAMIC_FUNC0(BinReader_obj,eof,return )

::String BinReader_obj::hexU32(int v){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_31_hexU32)
HXDLIN(  31)		return ::StringTools_obj::hex(v,8).toLowerCase();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(BinReader_obj,hexU32,return )

int BinReader_obj::parseHex(::String s){
            	HX_STACKFRAME(&_hx_pos_442cef72209386ca_36_parseHex)
HXDLIN(  36)		return ( (int)(::Std_obj::parseInt((HX_("0x",48,2a,00,00) + s))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(BinReader_obj,parseHex,return )


::hx::ObjectPtr< BinReader_obj > BinReader_obj::__new( ::haxe::io::Bytes b) {
	::hx::ObjectPtr< BinReader_obj > __this = new BinReader_obj();
	__this->__construct(b);
	return __this;
}

::hx::ObjectPtr< BinReader_obj > BinReader_obj::__alloc(::hx::Ctx *_hx_ctx, ::haxe::io::Bytes b) {
	BinReader_obj *__this = (BinReader_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(BinReader_obj), true, "BinReader"));
	*(void **)__this = BinReader_obj::_hx_vtable;
	__this->__construct(b);
	return __this;
}

BinReader_obj::BinReader_obj()
{
}

void BinReader_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(BinReader);
	HX_MARK_MEMBER_NAME(bi,"bi");
	HX_MARK_END_CLASS();
}

void BinReader_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(bi,"bi");
}

::hx::Val BinReader_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 2:
		if (HX_FIELD_EQ(inName,"bi") ) { return ::hx::Val( bi ); }
		break;
	case 3:
		if (HX_FIELD_EQ(inName,"pos") ) { return ::hx::Val( pos_dyn() ); }
		if (HX_FIELD_EQ(inName,"eof") ) { return ::hx::Val( eof_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"skip") ) { return ::hx::Val( skip_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"readI32") ) { return ::hx::Val( readI32_dyn() ); }
		if (HX_FIELD_EQ(inName,"readU32") ) { return ::hx::Val( readU32_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"readBool") ) { return ::hx::Val( readBool_dyn() ); }
		if (HX_FIELD_EQ(inName,"readUtf8") ) { return ::hx::Val( readUtf8_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"readBytes") ) { return ::hx::Val( readBytes_dyn() ); }
		if (HX_FIELD_EQ(inName,"remaining") ) { return ::hx::Val( remaining_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

bool BinReader_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 6:
		if (HX_FIELD_EQ(inName,"hexU32") ) { outValue = hexU32_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"parseHex") ) { outValue = parseHex_dyn(); return true; }
	}
	return false;
}

::hx::Val BinReader_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 2:
		if (HX_FIELD_EQ(inName,"bi") ) { bi=inValue.Cast<  ::haxe::io::BytesInput >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void BinReader_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("bi",c7,55,00,00));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo BinReader_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::io::BytesInput */ ,(int)offsetof(BinReader_obj,bi),HX_("bi",c7,55,00,00)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *BinReader_obj_sStaticStorageInfo = 0;
#endif

static ::String BinReader_obj_sMemberFields[] = {
	HX_("bi",c7,55,00,00),
	HX_("readI32",92,7f,c9,02),
	HX_("readU32",9e,9a,d2,02),
	HX_("readBool",a0,5e,13,69),
	HX_("readBytes",35,55,7f,8e),
	HX_("readUtf8",a7,2f,a6,75),
	HX_("skip",7f,16,55,4c),
	HX_("pos",94,5d,55,00),
	HX_("remaining",f6,c6,c1,bb),
	HX_("eof",bc,04,4d,00),
	::String(null()) };

::hx::Class BinReader_obj::__mClass;

static ::String BinReader_obj_sStaticFields[] = {
	HX_("hexU32",39,64,28,0c),
	HX_("parseHex",68,4c,71,d6),
	::String(null())
};

void BinReader_obj::__register()
{
	BinReader_obj _hx_dummy;
	BinReader_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("BinReader",4a,01,4d,e7);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &BinReader_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(BinReader_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(BinReader_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< BinReader_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = BinReader_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = BinReader_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

