// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_BinWriter
#include <BinWriter.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_BytesBuffer
#include <haxe/io/BytesBuffer.h>
#endif
#ifndef INCLUDED_haxe_io_BytesOutput
#include <haxe/io/BytesOutput.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_7c2a3e435c936466_9_new,"BinWriter","new",0x0d65b8ac,"BinWriter.new","BinWriter.hx",9,0x79bf0044)
HX_LOCAL_STACK_FRAME(_hx_pos_7c2a3e435c936466_14_writeI32,"BinWriter","writeI32",0x4814bddd,"BinWriter.writeI32","BinWriter.hx",14,0x79bf0044)
HX_LOCAL_STACK_FRAME(_hx_pos_7c2a3e435c936466_15_writeBool,"BinWriter","writeBool",0xc59ea1f5,"BinWriter.writeBool","BinWriter.hx",15,0x79bf0044)
HX_LOCAL_STACK_FRAME(_hx_pos_7c2a3e435c936466_18_writeBytes,"BinWriter","writeBytes",0x2bcefc40,"BinWriter.writeBytes","BinWriter.hx",18,0x79bf0044)
HX_LOCAL_STACK_FRAME(_hx_pos_7c2a3e435c936466_21_writeUtf8,"BinWriter","writeUtf8",0xd23172fc,"BinWriter.writeUtf8","BinWriter.hx",21,0x79bf0044)
HX_LOCAL_STACK_FRAME(_hx_pos_7c2a3e435c936466_26_len,"BinWriter","len",0x0d643421,"BinWriter.len","BinWriter.hx",26,0x79bf0044)
HX_LOCAL_STACK_FRAME(_hx_pos_7c2a3e435c936466_27_get,"BinWriter","get",0x0d6068e2,"BinWriter.get","BinWriter.hx",27,0x79bf0044)

void BinWriter_obj::__construct(){
            	HX_GC_STACKFRAME(&_hx_pos_7c2a3e435c936466_9_new)
HXLINE(  10)		this->bo =  ::haxe::io::BytesOutput_obj::__alloc( HX_CTX );
HXLINE(  11)		this->bo->set_bigEndian(false);
            	}

Dynamic BinWriter_obj::__CreateEmpty() { return new BinWriter_obj; }

void *BinWriter_obj::_hx_vtable = 0;

Dynamic BinWriter_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< BinWriter_obj > _hx_result = new BinWriter_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool BinWriter_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x2be4a7fa;
}

void BinWriter_obj::writeI32(int v){
            	HX_STACKFRAME(&_hx_pos_7c2a3e435c936466_14_writeI32)
HXDLIN(  14)		this->bo->writeInt32(v);
            	}


HX_DEFINE_DYNAMIC_FUNC1(BinWriter_obj,writeI32,(void))

void BinWriter_obj::writeBool(bool v){
            	HX_STACKFRAME(&_hx_pos_7c2a3e435c936466_15_writeBool)
HXDLIN(  15)		int _hx_tmp;
HXDLIN(  15)		if (v) {
HXDLIN(  15)			_hx_tmp = 1;
            		}
            		else {
HXDLIN(  15)			_hx_tmp = 0;
            		}
HXDLIN(  15)		this->bo->writeByte(_hx_tmp);
            	}


HX_DEFINE_DYNAMIC_FUNC1(BinWriter_obj,writeBool,(void))

void BinWriter_obj::writeBytes( ::haxe::io::Bytes b){
            	HX_STACKFRAME(&_hx_pos_7c2a3e435c936466_18_writeBytes)
HXDLIN(  18)		this->bo->writeBytes(b,0,b->length);
            	}


HX_DEFINE_DYNAMIC_FUNC1(BinWriter_obj,writeBytes,(void))

void BinWriter_obj::writeUtf8(::String s){
            	HX_STACKFRAME(&_hx_pos_7c2a3e435c936466_21_writeUtf8)
HXLINE(  22)		 ::haxe::io::Bytes b = ::haxe::io::Bytes_obj::ofString(s,null());
HXLINE(  23)		this->bo->writeBytes(b,0,b->length);
            	}


HX_DEFINE_DYNAMIC_FUNC1(BinWriter_obj,writeUtf8,(void))

int BinWriter_obj::len(){
            	HX_STACKFRAME(&_hx_pos_7c2a3e435c936466_26_len)
HXDLIN(  26)		return this->bo->b->b->length;
            	}


HX_DEFINE_DYNAMIC_FUNC0(BinWriter_obj,len,return )

 ::haxe::io::Bytes BinWriter_obj::get(){
            	HX_STACKFRAME(&_hx_pos_7c2a3e435c936466_27_get)
HXDLIN(  27)		return this->bo->getBytes();
            	}


HX_DEFINE_DYNAMIC_FUNC0(BinWriter_obj,get,return )


::hx::ObjectPtr< BinWriter_obj > BinWriter_obj::__new() {
	::hx::ObjectPtr< BinWriter_obj > __this = new BinWriter_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< BinWriter_obj > BinWriter_obj::__alloc(::hx::Ctx *_hx_ctx) {
	BinWriter_obj *__this = (BinWriter_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(BinWriter_obj), true, "BinWriter"));
	*(void **)__this = BinWriter_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

BinWriter_obj::BinWriter_obj()
{
}

void BinWriter_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(BinWriter);
	HX_MARK_MEMBER_NAME(bo,"bo");
	HX_MARK_END_CLASS();
}

void BinWriter_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(bo,"bo");
}

::hx::Val BinWriter_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 2:
		if (HX_FIELD_EQ(inName,"bo") ) { return ::hx::Val( bo ); }
		break;
	case 3:
		if (HX_FIELD_EQ(inName,"len") ) { return ::hx::Val( len_dyn() ); }
		if (HX_FIELD_EQ(inName,"get") ) { return ::hx::Val( get_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"writeI32") ) { return ::hx::Val( writeI32_dyn() ); }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"writeBool") ) { return ::hx::Val( writeBool_dyn() ); }
		if (HX_FIELD_EQ(inName,"writeUtf8") ) { return ::hx::Val( writeUtf8_dyn() ); }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"writeBytes") ) { return ::hx::Val( writeBytes_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val BinWriter_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 2:
		if (HX_FIELD_EQ(inName,"bo") ) { bo=inValue.Cast<  ::haxe::io::BytesOutput >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void BinWriter_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("bo",cd,55,00,00));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo BinWriter_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::io::BytesOutput */ ,(int)offsetof(BinWriter_obj,bo),HX_("bo",cd,55,00,00)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *BinWriter_obj_sStaticStorageInfo = 0;
#endif

static ::String BinWriter_obj_sMemberFields[] = {
	HX_("bo",cd,55,00,00),
	HX_("writeI32",a9,39,f0,23),
	HX_("writeBool",a9,78,cf,49),
	HX_("writeBytes",0c,03,5a,52),
	HX_("writeUtf8",b0,49,62,56),
	HX_("len",d5,4b,52,00),
	HX_("get",96,80,4e,00),
	::String(null()) };

::hx::Class BinWriter_obj::__mClass;

void BinWriter_obj::__register()
{
	BinWriter_obj _hx_dummy;
	BinWriter_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("BinWriter",ba,32,a1,68);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(BinWriter_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< BinWriter_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = BinWriter_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = BinWriter_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

