// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_FS
#include <FS.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_haxe_format_JsonParser
#include <haxe/format/JsonParser.h>
#endif
#ifndef INCLUDED_haxe_format_JsonPrinter
#include <haxe/format/JsonPrinter.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_Path
#include <haxe/io/Path.h>
#endif
#ifndef INCLUDED_sys_FileSystem
#include <sys/FileSystem.h>
#endif
#ifndef INCLUDED_sys_io_File
#include <sys/io/File.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_11_mkdirs,"FS","mkdirs",0x2568d9e5,"FS.mkdirs","FS.hx",11,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_18_mkdir,"FS","mkdir",0x8d5e9ace,"FS.mkdir","FS.hx",18,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_22_exists,"FS","exists",0x72192add,"FS.exists","FS.hx",22,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_30_subdirs,"FS","subdirs",0x654623e5,"FS.subdirs","FS.hx",30,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_26_subdirs,"FS","subdirs",0x654623e5,"FS.subdirs","FS.hx",26,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_39_files,"FS","files",0x84442c96,"FS.files","FS.hx",39,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_35_files,"FS","files",0x84442c96,"FS.files","FS.hx",35,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_43_join,"FS","join",0x51514eab,"FS.join","FS.hx",43,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_52_readBytes,"FS","readBytes",0xde559ed4,"FS.readBytes","FS.hx",52,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_56_writeBytes,"FS","writeBytes",0xde04248d,"FS.writeBytes","FS.hx",56,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_60_readJson,"FS","readJson",0xeab72bdf,"FS.readJson","FS.hx",60,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_64_writeJson,"FS","writeJson",0x9ef28046,"FS.writeJson","FS.hx",64,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_70_hex8,"FS","hex8",0x4ff757be,"FS.hex8","FS.hx",70,0x850c9391)
HX_LOCAL_STACK_FRAME(_hx_pos_e689dd07e824ad0d_79_unhex8,"FS","unhex8",0x151950d7,"FS.unhex8","FS.hx",79,0x850c9391)

void FS_obj::__construct() { }

Dynamic FS_obj::__CreateEmpty() { return new FS_obj; }

void *FS_obj::_hx_vtable = 0;

Dynamic FS_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< FS_obj > _hx_result = new FS_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool FS_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x2682a00d;
}

void FS_obj::mkdirs(::String path){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_11_mkdirs)
HXLINE(  12)		bool _hx_tmp;
HXDLIN(  12)		bool _hx_tmp1;
HXDLIN(  12)		if ((path != HX_("",00,00,00,00))) {
HXLINE(  12)			_hx_tmp1 = (path == HX_(".",2e,00,00,00));
            		}
            		else {
HXLINE(  12)			_hx_tmp1 = true;
            		}
HXDLIN(  12)		if (!(_hx_tmp1)) {
HXLINE(  12)			_hx_tmp = ::sys::FileSystem_obj::exists(path);
            		}
            		else {
HXLINE(  12)			_hx_tmp = true;
            		}
HXDLIN(  12)		if (_hx_tmp) {
HXLINE(  12)			return;
            		}
HXLINE(  13)		::FS_obj::mkdirs(::haxe::io::Path_obj::directory(path));
HXLINE(  14)		::sys::FileSystem_obj::createDirectory(path);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,mkdirs,(void))

void FS_obj::mkdir(::String path){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_18_mkdir)
HXDLIN(  18)		if (!(::sys::FileSystem_obj::exists(path))) {
HXDLIN(  18)			::sys::FileSystem_obj::createDirectory(path);
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,mkdir,(void))

bool FS_obj::exists(::String path){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_22_exists)
HXDLIN(  22)		return ::sys::FileSystem_obj::exists(path);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,exists,return )

::Array< ::String > FS_obj::subdirs(::String path){
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(2)
            		int _hx_run(::String a,::String b){
            			HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_30_subdirs)
HXLINE(  30)			if ((a < b)) {
HXLINE(  30)				return -1;
            			}
            			else {
HXLINE(  30)				if ((a > b)) {
HXLINE(  30)					return 1;
            				}
            				else {
HXLINE(  30)					return 0;
            				}
            			}
HXDLIN(  30)			return 0;
            		}
            		HX_END_LOCAL_FUNC2(return)

            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_26_subdirs)
HXLINE(  27)		if (!(::sys::FileSystem_obj::exists(path))) {
HXLINE(  27)			return ::Array_obj< ::String >::__new(0);
            		}
HXLINE(  28)		::Array< ::String > _g = ::Array_obj< ::String >::__new(0);
HXDLIN(  28)		{
HXLINE(  28)			int _g1 = 0;
HXDLIN(  28)			::Array< ::String > _g2 = ::sys::FileSystem_obj::readDirectory(path);
HXDLIN(  28)			while((_g1 < _g2->length)){
HXLINE(  28)				::String v = _g2->__get(_g1);
HXDLIN(  28)				_g1 = (_g1 + 1);
HXDLIN(  28)				if (::sys::FileSystem_obj::isDirectory(((path + HX_("/",2f,00,00,00)) + v))) {
HXLINE(  28)					_g->push(v);
            				}
            			}
            		}
HXDLIN(  28)		::Array< ::String > result = _g;
HXLINE(  30)		result->sort( ::Dynamic(new _hx_Closure_0()));
HXLINE(  31)		return result;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,subdirs,return )

::Array< ::String > FS_obj::files(::String path){
            		HX_BEGIN_LOCAL_FUNC_S0(::hx::LocalFunc,_hx_Closure_0) HXARGC(2)
            		int _hx_run(::String a,::String b){
            			HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_39_files)
HXLINE(  39)			if ((a < b)) {
HXLINE(  39)				return -1;
            			}
            			else {
HXLINE(  39)				if ((a > b)) {
HXLINE(  39)					return 1;
            				}
            				else {
HXLINE(  39)					return 0;
            				}
            			}
HXDLIN(  39)			return 0;
            		}
            		HX_END_LOCAL_FUNC2(return)

            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_35_files)
HXLINE(  36)		if (!(::sys::FileSystem_obj::exists(path))) {
HXLINE(  36)			return ::Array_obj< ::String >::__new(0);
            		}
HXLINE(  37)		::Array< ::String > _g = ::Array_obj< ::String >::__new(0);
HXDLIN(  37)		{
HXLINE(  37)			int _g1 = 0;
HXDLIN(  37)			::Array< ::String > _g2 = ::sys::FileSystem_obj::readDirectory(path);
HXDLIN(  37)			while((_g1 < _g2->length)){
HXLINE(  37)				::String v = _g2->__get(_g1);
HXDLIN(  37)				_g1 = (_g1 + 1);
HXDLIN(  37)				if (!(::sys::FileSystem_obj::isDirectory(((path + HX_("/",2f,00,00,00)) + v)))) {
HXLINE(  37)					_g->push(v);
            				}
            			}
            		}
HXDLIN(  37)		::Array< ::String > result = _g;
HXLINE(  39)		result->sort( ::Dynamic(new _hx_Closure_0()));
HXLINE(  40)		return result;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,files,return )

::String FS_obj::join(::String a,::String b){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_43_join)
HXLINE(  44)		if ((a == HX_("",00,00,00,00))) {
HXLINE(  44)			return b;
            		}
HXLINE(  45)		if ((a.charAt((a.length - 1)) == HX_("/",2f,00,00,00))) {
HXLINE(  45)			return (a + b);
            		}
HXLINE(  46)		return ((a + HX_("/",2f,00,00,00)) + b);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(FS_obj,join,return )

 ::haxe::io::Bytes FS_obj::readBytes(::String path){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_52_readBytes)
HXDLIN(  52)		return ::sys::io::File_obj::getBytes(path);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,readBytes,return )

void FS_obj::writeBytes(::String path, ::haxe::io::Bytes b){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_56_writeBytes)
HXDLIN(  56)		::sys::io::File_obj::saveBytes(path,b);
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(FS_obj,writeBytes,(void))

 ::Dynamic FS_obj::readJson(::String path){
            	HX_GC_STACKFRAME(&_hx_pos_e689dd07e824ad0d_60_readJson)
HXDLIN(  60)		return  ::haxe::format::JsonParser_obj::__alloc( HX_CTX ,::sys::io::File_obj::getContent(path))->doParse();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,readJson,return )

void FS_obj::writeJson(::String path, ::Dynamic v){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_64_writeJson)
HXDLIN(  64)		 ::Dynamic replacer = null();
HXDLIN(  64)		::sys::io::File_obj::saveContent(path,::haxe::format::JsonPrinter_obj::print(v,replacer,HX_("  ",00,1c,00,00)));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC2(FS_obj,writeJson,(void))

::String FS_obj::hex8(int v){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_70_hex8)
HXLINE(  72)		int hi = (::hx::UShr(v,16) & 65535);
HXLINE(  73)		int lo = (v & 65535);
HXLINE(  74)		::String _hx_tmp = ::StringTools_obj::hex(hi,4).toLowerCase();
HXDLIN(  74)		return (_hx_tmp + ::StringTools_obj::hex(lo,4).toLowerCase());
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,hex8,return )

int FS_obj::unhex8(::String s){
            	HX_STACKFRAME(&_hx_pos_e689dd07e824ad0d_79_unhex8)
HXDLIN(  79)		return ( (int)(::Std_obj::parseInt((HX_("0x",48,2a,00,00) + s))) );
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(FS_obj,unhex8,return )


FS_obj::FS_obj()
{
}

bool FS_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"join") ) { outValue = join_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"hex8") ) { outValue = hex8_dyn(); return true; }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"mkdir") ) { outValue = mkdir_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"files") ) { outValue = files_dyn(); return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"mkdirs") ) { outValue = mkdirs_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"exists") ) { outValue = exists_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"unhex8") ) { outValue = unhex8_dyn(); return true; }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"subdirs") ) { outValue = subdirs_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"readJson") ) { outValue = readJson_dyn(); return true; }
		break;
	case 9:
		if (HX_FIELD_EQ(inName,"readBytes") ) { outValue = readBytes_dyn(); return true; }
		if (HX_FIELD_EQ(inName,"writeJson") ) { outValue = writeJson_dyn(); return true; }
		break;
	case 10:
		if (HX_FIELD_EQ(inName,"writeBytes") ) { outValue = writeBytes_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *FS_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *FS_obj_sStaticStorageInfo = 0;
#endif

::hx::Class FS_obj::__mClass;

static ::String FS_obj_sStaticFields[] = {
	HX_("mkdirs",e4,cc,2f,73),
	HX_("mkdir",af,4c,b3,09),
	HX_("exists",dc,1d,e0,bf),
	HX_("subdirs",06,d0,93,25),
	HX_("files",77,de,98,00),
	HX_("join",ea,33,65,46),
	HX_("readBytes",35,55,7f,8e),
	HX_("writeBytes",0c,03,5a,52),
	HX_("readJson",9e,1c,60,6e),
	HX_("writeJson",a7,36,1c,4f),
	HX_("hex8",fd,3c,0b,45),
	HX_("unhex8",d6,43,e0,62),
	::String(null())
};

void FS_obj::__register()
{
	FS_obj _hx_dummy;
	FS_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("FS",4d,3d,00,00);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &FS_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(FS_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< FS_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = FS_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = FS_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

