// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_MetaDataType
#include <MetaDataType.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_41393999268bda8b_9_name,"MetaDataType","name",0x899d2ed0,"MetaDataType.name","MetaDataType.hx",9,0x419f7c55)
HX_LOCAL_STACK_FRAME(_hx_pos_41393999268bda8b_18_ext,"MetaDataType","ext",0x29eb07bc,"MetaDataType.ext","MetaDataType.hx",18,0x419f7c55)
HX_LOCAL_STACK_FRAME(_hx_pos_41393999268bda8b_3_boot,"MetaDataType","boot",0x81b940b7,"MetaDataType.boot","MetaDataType.hx",3,0x419f7c55)
HX_LOCAL_STACK_FRAME(_hx_pos_41393999268bda8b_4_boot,"MetaDataType","boot",0x81b940b7,"MetaDataType.boot","MetaDataType.hx",4,0x419f7c55)
HX_LOCAL_STACK_FRAME(_hx_pos_41393999268bda8b_5_boot,"MetaDataType","boot",0x81b940b7,"MetaDataType.boot","MetaDataType.hx",5,0x419f7c55)
HX_LOCAL_STACK_FRAME(_hx_pos_41393999268bda8b_6_boot,"MetaDataType","boot",0x81b940b7,"MetaDataType.boot","MetaDataType.hx",6,0x419f7c55)

void MetaDataType_obj::__construct() { }

Dynamic MetaDataType_obj::__CreateEmpty() { return new MetaDataType_obj; }

void *MetaDataType_obj::_hx_vtable = 0;

Dynamic MetaDataType_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< MetaDataType_obj > _hx_result = new MetaDataType_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool MetaDataType_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x2ee5ac2d;
}

int MetaDataType_obj::UNKNOWN;

int MetaDataType_obj::JSON;

int MetaDataType_obj::BINARY;

int MetaDataType_obj::PROTOBUF;

::String MetaDataType_obj::name(int v){
            	HX_STACKFRAME(&_hx_pos_41393999268bda8b_9_name)
HXDLIN(   9)		switch((int)(v)){
            			case (int)1: {
HXLINE(  10)				return HX_("JSON",28,0a,29,31);
            			}
            			break;
            			case (int)2: {
HXLINE(  11)				return HX_("BINARY",01,68,8e,9f);
            			}
            			break;
            			case (int)3: {
HXLINE(  12)				return HX_("PROTOBUF",4b,29,e8,59);
            			}
            			break;
            			default:{
HXLINE(  13)				return HX_("UNKNOWN",6a,f7,4e,61);
            			}
            		}
HXLINE(   9)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(MetaDataType_obj,name,return )

::String MetaDataType_obj::ext(int v){
            	HX_STACKFRAME(&_hx_pos_41393999268bda8b_18_ext)
HXDLIN(  18)		switch((int)(v)){
            			case (int)1: {
HXLINE(  19)				return HX_("json",28,42,68,46);
            			}
            			break;
            			case (int)3: {
HXLINE(  20)				return HX_("pb",f2,61,00,00);
            			}
            			break;
            			default:{
HXLINE(  21)				return HX_("bin",c7,b8,4a,00);
            			}
            		}
HXLINE(  18)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(MetaDataType_obj,ext,return )


MetaDataType_obj::MetaDataType_obj()
{
}

bool MetaDataType_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"ext") ) { outValue = ext_dyn(); return true; }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"name") ) { outValue = name_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *MetaDataType_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo MetaDataType_obj_sStaticStorageInfo[] = {
	{::hx::fsInt,(void *) &MetaDataType_obj::UNKNOWN,HX_("UNKNOWN",6a,f7,4e,61)},
	{::hx::fsInt,(void *) &MetaDataType_obj::JSON,HX_("JSON",28,0a,29,31)},
	{::hx::fsInt,(void *) &MetaDataType_obj::BINARY,HX_("BINARY",01,68,8e,9f)},
	{::hx::fsInt,(void *) &MetaDataType_obj::PROTOBUF,HX_("PROTOBUF",4b,29,e8,59)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void MetaDataType_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(MetaDataType_obj::UNKNOWN,"UNKNOWN");
	HX_MARK_MEMBER_NAME(MetaDataType_obj::JSON,"JSON");
	HX_MARK_MEMBER_NAME(MetaDataType_obj::BINARY,"BINARY");
	HX_MARK_MEMBER_NAME(MetaDataType_obj::PROTOBUF,"PROTOBUF");
};

#ifdef HXCPP_VISIT_ALLOCS
static void MetaDataType_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(MetaDataType_obj::UNKNOWN,"UNKNOWN");
	HX_VISIT_MEMBER_NAME(MetaDataType_obj::JSON,"JSON");
	HX_VISIT_MEMBER_NAME(MetaDataType_obj::BINARY,"BINARY");
	HX_VISIT_MEMBER_NAME(MetaDataType_obj::PROTOBUF,"PROTOBUF");
};

#endif

::hx::Class MetaDataType_obj::__mClass;

static ::String MetaDataType_obj_sStaticFields[] = {
	HX_("UNKNOWN",6a,f7,4e,61),
	HX_("JSON",28,0a,29,31),
	HX_("BINARY",01,68,8e,9f),
	HX_("PROTOBUF",4b,29,e8,59),
	HX_("name",4b,72,ff,48),
	HX_("ext",a1,0c,4d,00),
	::String(null())
};

void MetaDataType_obj::__register()
{
	MetaDataType_obj _hx_dummy;
	MetaDataType_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("MetaDataType",09,f2,b9,13);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &MetaDataType_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = MetaDataType_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(MetaDataType_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< MetaDataType_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = MetaDataType_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = MetaDataType_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = MetaDataType_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void MetaDataType_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_41393999268bda8b_3_boot)
HXDLIN(   3)		UNKNOWN = 0;
            	}
{
            	HX_STACKFRAME(&_hx_pos_41393999268bda8b_4_boot)
HXDLIN(   4)		JSON = 1;
            	}
{
            	HX_STACKFRAME(&_hx_pos_41393999268bda8b_5_boot)
HXDLIN(   5)		BINARY = 2;
            	}
{
            	HX_STACKFRAME(&_hx_pos_41393999268bda8b_6_boot)
HXDLIN(   6)		PROTOBUF = 3;
            	}
}

