// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_PCFBlockTypes
#include <PCFBlockTypes.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_01c27ee13e81bed4_3_boot,"PCFBlockTypes","boot",0x81d14a41,"PCFBlockTypes.boot","PCFBlockTypes.hx",3,0x409d2f5f)
HX_LOCAL_STACK_FRAME(_hx_pos_01c27ee13e81bed4_4_boot,"PCFBlockTypes","boot",0x81d14a41,"PCFBlockTypes.boot","PCFBlockTypes.hx",4,0x409d2f5f)
HX_LOCAL_STACK_FRAME(_hx_pos_01c27ee13e81bed4_5_boot,"PCFBlockTypes","boot",0x81d14a41,"PCFBlockTypes.boot","PCFBlockTypes.hx",5,0x409d2f5f)

void PCFBlockTypes_obj::__construct() { }

Dynamic PCFBlockTypes_obj::__CreateEmpty() { return new PCFBlockTypes_obj; }

void *PCFBlockTypes_obj::_hx_vtable = 0;

Dynamic PCFBlockTypes_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< PCFBlockTypes_obj > _hx_result = new PCFBlockTypes_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool PCFBlockTypes_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x033969ff;
}

int PCFBlockTypes_obj::RESOURCE;

int PCFBlockTypes_obj::INDEX;

int PCFBlockTypes_obj::NODE;


PCFBlockTypes_obj::PCFBlockTypes_obj()
{
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *PCFBlockTypes_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo PCFBlockTypes_obj_sStaticStorageInfo[] = {
	{::hx::fsInt,(void *) &PCFBlockTypes_obj::RESOURCE,HX_("RESOURCE",ce,ec,25,6c)},
	{::hx::fsInt,(void *) &PCFBlockTypes_obj::INDEX,HX_("INDEX",f2,d2,02,3c)},
	{::hx::fsInt,(void *) &PCFBlockTypes_obj::NODE,HX_("NODE",02,d2,ca,33)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void PCFBlockTypes_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(PCFBlockTypes_obj::RESOURCE,"RESOURCE");
	HX_MARK_MEMBER_NAME(PCFBlockTypes_obj::INDEX,"INDEX");
	HX_MARK_MEMBER_NAME(PCFBlockTypes_obj::NODE,"NODE");
};

#ifdef HXCPP_VISIT_ALLOCS
static void PCFBlockTypes_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(PCFBlockTypes_obj::RESOURCE,"RESOURCE");
	HX_VISIT_MEMBER_NAME(PCFBlockTypes_obj::INDEX,"INDEX");
	HX_VISIT_MEMBER_NAME(PCFBlockTypes_obj::NODE,"NODE");
};

#endif

::hx::Class PCFBlockTypes_obj::__mClass;

static ::String PCFBlockTypes_obj_sStaticFields[] = {
	HX_("RESOURCE",ce,ec,25,6c),
	HX_("INDEX",f2,d2,02,3c),
	HX_("NODE",02,d2,ca,33),
	::String(null())
};

void PCFBlockTypes_obj::__register()
{
	PCFBlockTypes_obj _hx_dummy;
	PCFBlockTypes_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("PCFBlockTypes",bf,54,f2,26);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mMarkFunc = PCFBlockTypes_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(PCFBlockTypes_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< PCFBlockTypes_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = PCFBlockTypes_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = PCFBlockTypes_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = PCFBlockTypes_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void PCFBlockTypes_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_01c27ee13e81bed4_3_boot)
HXDLIN(   3)		RESOURCE = 0;
            	}
{
            	HX_STACKFRAME(&_hx_pos_01c27ee13e81bed4_4_boot)
HXDLIN(   4)		INDEX = 1;
            	}
{
            	HX_STACKFRAME(&_hx_pos_01c27ee13e81bed4_5_boot)
HXDLIN(   5)		NODE = 2;
            	}
}

