// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_PCFfileType
#include <PCFfileType.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_7c994e4d691e05d1_4_name,"PCFfileType","name",0x0ea4e390,"PCFfileType.name","PCFfileType.hx",4,0x9dcc8115)

void PCFfileType_obj::__construct() { }

Dynamic PCFfileType_obj::__CreateEmpty() { return new PCFfileType_obj; }

void *PCFfileType_obj::_hx_vtable = 0;

Dynamic PCFfileType_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< PCFfileType_obj > _hx_result = new PCFfileType_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool PCFfileType_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x6049ba89;
}

::String PCFfileType_obj::name(int v){
            	HX_STACKFRAME(&_hx_pos_7c994e4d691e05d1_4_name)
HXDLIN(   4)		switch((int)(v)){
            			case (int)0: {
HXLINE(   5)				return HX_("None",d8,3e,e3,33);
            			}
            			break;
            			case (int)1: {
HXLINE(   6)				return HX_("Actor",d5,3a,d4,ae);
            			}
            			break;
            			case (int)2: {
HXLINE(   7)				return HX_("Scene",2c,49,ff,0b);
            			}
            			break;
            			case (int)3: {
HXLINE(   8)				return HX_("CCItem",d3,fb,5a,8e);
            			}
            			break;
            			case (int)4: {
HXLINE(   9)				return HX_("Avatar",39,f4,f0,2e);
            			}
            			break;
            			case (int)5: {
HXLINE(  10)				return HX_("Music",85,40,88,a3);
            			}
            			break;
            			case (int)6: {
HXLINE(  11)				return HX_("SoundEffect",a0,f8,02,f8);
            			}
            			break;
            			case (int)7: {
HXLINE(  12)				return HX_("Animation",e4,ce,07,ed);
            			}
            			break;
            			default:{
HXLINE(  13)				return (HX_("Unknown_",b5,b1,f5,43) + v);
            			}
            		}
HXLINE(   4)		return null();
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(PCFfileType_obj,name,return )


PCFfileType_obj::PCFfileType_obj()
{
}

bool PCFfileType_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"name") ) { outValue = name_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *PCFfileType_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *PCFfileType_obj_sStaticStorageInfo = 0;
#endif

::hx::Class PCFfileType_obj::__mClass;

static ::String PCFfileType_obj_sStaticFields[] = {
	HX_("name",4b,72,ff,48),
	::String(null())
};

void PCFfileType_obj::__register()
{
	PCFfileType_obj _hx_dummy;
	PCFfileType_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("PCFfileType",49,75,4e,ad);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &PCFfileType_obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(PCFfileType_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< PCFfileType_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = PCFfileType_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = PCFfileType_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

