// Generated by Haxe 4.3.7
#include <hxcpp.h>

#ifndef INCLUDED_RT
#include <RT.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_haxe_ds_IntMap
#include <haxe/ds/IntMap.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_49_init,"RT","init",0xaa04433c,"RT.init","RT.hx",49,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_90_toName,"RT","toName",0x4d754892,"RT.toName","RT.hx",90,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_97_fromName,"RT","fromName",0xedd9cf01,"RT.fromName","RT.hx",97,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_12_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",12,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_13_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",13,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_14_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",14,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_15_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",15,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_16_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",16,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_17_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",17,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_18_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",18,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_19_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",19,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_20_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",20,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_21_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",21,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_22_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",22,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_23_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",23,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_24_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",24,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_25_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",25,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_26_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",26,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_27_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",27,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_28_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",28,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_29_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",29,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_30_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",30,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_31_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",31,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_32_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",32,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_33_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",33,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_34_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",34,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_35_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",35,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_36_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",36,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_37_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",37,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_38_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",38,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_39_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",39,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_40_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",40,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_42_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",42,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_43_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",43,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_44_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",44,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_46_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",46,0x6e84c03c)
HX_LOCAL_STACK_FRAME(_hx_pos_3d74350a37f62501_47_boot,"RT","boot",0xa5648c5e,"RT.boot","RT.hx",47,0x6e84c03c)

void RT_obj::__construct() { }

Dynamic RT_obj::__CreateEmpty() { return new RT_obj; }

void *RT_obj::_hx_vtable = 0;

Dynamic RT_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< RT_obj > _hx_result = new RT_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool RT_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x2682aa82;
}

int RT_obj::NONE;

int RT_obj::OBJECT;

int RT_obj::ROOT;

int RT_obj::NODE;

int RT_obj::INDEX;

int RT_obj::SCRIPT;

int RT_obj::MESH;

int RT_obj::SKINNEDMESH;

int RT_obj::TRANSFORM;

int RT_obj::ANIMATOR;

int RT_obj::AVATARREFERENCE;

int RT_obj::ANIMATION;

int RT_obj::MATERIAL;

int RT_obj::MATERIALPOINTER;

int RT_obj::TRANSFORMPOINTER;

int RT_obj::TEXTURE;

int RT_obj::LIGHT;

int RT_obj::LIGHTPROBES;

int RT_obj::INTERNALBUNDLE;

int RT_obj::CAMERA;

int RT_obj::COLLIDER;

int RT_obj::AUDIO;

int RT_obj::WEIGHTS;

int RT_obj::PRIMITIVE;

int RT_obj::COLLECTION;

int RT_obj::POINTERCOLLECTION;

int RT_obj::CLASS;

int RT_obj::GRADIENT;

int RT_obj::ANIMATIONCLIP;

int RT_obj::ANIMATIONCLIPREFERENCE;

int RT_obj::ANIMATIONLOADER;

int RT_obj::GRIDCLUSTER;

 ::haxe::ds::StringMap RT_obj::_n2v;

 ::haxe::ds::IntMap RT_obj::_v2n;

void RT_obj::init(){
            	HX_GC_STACKFRAME(&_hx_pos_3d74350a37f62501_49_init)
HXLINE(  50)		if (::hx::IsNotNull( ::RT_obj::_n2v )) {
HXLINE(  50)			return;
            		}
HXLINE(  51)		::Array< ::Dynamic> pairs = ::Array_obj< ::Dynamic>::__new(32)->init(0, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("NONE",b8,da,ca,33))
            			->setFixed(1,HX_("v",76,00,00,00),0)))->init(1, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("OBJECT",bf,2a,c2,c7))
            			->setFixed(1,HX_("v",76,00,00,00),1)))->init(2, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("ROOT",22,b6,6f,36))
            			->setFixed(1,HX_("v",76,00,00,00),2)))->init(3, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("NODE",02,d2,ca,33))
            			->setFixed(1,HX_("v",76,00,00,00),4)))->init(4, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("INDEX",f2,d2,02,3c))
            			->setFixed(1,HX_("v",76,00,00,00),8)))->init(5, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("SCRIPT",0b,fa,e2,f9))
            			->setFixed(1,HX_("v",76,00,00,00),16)))->init(6, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("MESH",ed,11,1a,33))
            			->setFixed(1,HX_("v",76,00,00,00),32)))->init(7, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("SKINNEDMESH",bd,33,a7,4e))
            			->setFixed(1,HX_("v",76,00,00,00),64)))->init(8, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("TRANSFORM",4c,9d,eb,40))
            			->setFixed(1,HX_("v",76,00,00,00),128)))->init(9, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("ANIMATOR",67,0b,78,e2))
            			->setFixed(1,HX_("v",76,00,00,00),256)))->init(10, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("AVATARREFERENCE",72,80,3e,29))
            			->setFixed(1,HX_("v",76,00,00,00),512)))->init(11, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("ANIMATION",e4,5e,8d,46))
            			->setFixed(1,HX_("v",76,00,00,00),1024)))->init(12, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("MATERIAL",a7,ec,2a,4a))
            			->setFixed(1,HX_("v",76,00,00,00),2048)))->init(13, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("MATERIALPOINTER",d6,9a,28,51))
            			->setFixed(1,HX_("v",76,00,00,00),4096)))->init(14, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("TRANSFORMPOINTER",d1,78,61,3e))
            			->setFixed(1,HX_("v",76,00,00,00),8192)))->init(15, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("TEXTURE",bb,9c,b4,1e))
            			->setFixed(1,HX_("v",76,00,00,00),16384)))->init(16, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("LIGHT",b6,c8,ea,f2))
            			->setFixed(1,HX_("v",76,00,00,00),32768)))->init(17, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("LIGHTPROBES",79,d0,45,bb))
            			->setFixed(1,HX_("v",76,00,00,00),65536)))->init(18, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("INTERNALBUNDLE",7f,22,cc,56))
            			->setFixed(1,HX_("v",76,00,00,00),131072)))->init(19, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("CAMERA",a5,f2,0e,6a))
            			->setFixed(1,HX_("v",76,00,00,00),262144)))->init(20, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("COLLIDER",34,6f,5b,23))
            			->setFixed(1,HX_("v",76,00,00,00),524288)))->init(21, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("AUDIO",b6,b0,6e,a5))
            			->setFixed(1,HX_("v",76,00,00,00),1048576)))->init(22, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("WEIGHTS",db,ab,d0,ef))
            			->setFixed(1,HX_("v",76,00,00,00),2097152)))->init(23, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("PRIMITIVE",87,f8,b0,22))
            			->setFixed(1,HX_("v",76,00,00,00),4194304)))->init(24, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("COLLECTION",5e,42,8c,21))
            			->setFixed(1,HX_("v",76,00,00,00),8388608)))->init(25, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("POINTERCOLLECTION",3b,9d,2a,35))
            			->setFixed(1,HX_("v",76,00,00,00),16777216)))->init(26, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("CLASS",18,b0,46,c6))
            			->setFixed(1,HX_("v",76,00,00,00),33554432)))->init(27, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("GRADIENT",f0,c9,c4,83))
            			->setFixed(1,HX_("v",76,00,00,00),67108864)))->init(28, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("ANIMATIONCLIP",b4,d7,73,2f))
            			->setFixed(1,HX_("v",76,00,00,00),134217728)))->init(29, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("ANIMATIONCLIPREFERENCE",77,09,53,df))
            			->setFixed(1,HX_("v",76,00,00,00),268435456)))->init(30, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("ANIMATIONLOADER",f7,95,f7,23))
            			->setFixed(1,HX_("v",76,00,00,00),536870912)))->init(31, ::Dynamic(::hx::Anon_obj::Create(2)
            			->setFixed(0,HX_("n",6e,00,00,00),HX_("GRIDCLUSTER",d4,e4,30,1b))
            			->setFixed(1,HX_("v",76,00,00,00),(int)1073741824)));
HXLINE(  85)		::RT_obj::_n2v =  ::haxe::ds::StringMap_obj::__alloc( HX_CTX );
HXLINE(  86)		::RT_obj::_v2n =  ::haxe::ds::IntMap_obj::__alloc( HX_CTX );
HXLINE(  87)		{
HXLINE(  87)			int _g = 0;
HXDLIN(  87)			while((_g < pairs->length)){
HXLINE(  87)				 ::Dynamic p = pairs->__get(_g);
HXDLIN(  87)				_g = (_g + 1);
HXDLIN(  87)				{
HXLINE(  87)					int v = ( (int)(p->__Field(HX_("v",76,00,00,00),::hx::paccDynamic)) );
HXDLIN(  87)					::RT_obj::_n2v->set(( (::String)(p->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) ),v);
            				}
HXDLIN(  87)				{
HXLINE(  87)					::String v1 = ( (::String)(p->__Field(HX_("n",6e,00,00,00),::hx::paccDynamic)) );
HXDLIN(  87)					::RT_obj::_v2n->set(( (int)(p->__Field(HX_("v",76,00,00,00),::hx::paccDynamic)) ),v1);
            				}
            			}
            		}
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC0(RT_obj,init,(void))

::String RT_obj::toName(int v){
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_90_toName)
HXLINE(  91)		::RT_obj::init();
HXLINE(  92)		::String n = ::RT_obj::_v2n->get_string(v);
HXLINE(  93)		if (::hx::IsNotNull( n )) {
HXLINE(  93)			return n;
            		}
HXLINE(  94)		return (HX_("UNKNOWN_",b5,85,c9,c3) + ::StringTools_obj::hex(v,8));
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(RT_obj,toName,return )

int RT_obj::fromName(::String s){
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_97_fromName)
HXLINE(  98)		::RT_obj::init();
HXLINE(  99)		 ::Dynamic v = ::RT_obj::_n2v->get(s);
HXLINE( 100)		if (::hx::IsNotNull( v )) {
HXLINE( 100)			return ( (int)(v) );
            		}
HXLINE( 101)		if (::StringTools_obj::startsWith(s,HX_("UNKNOWN_",b5,85,c9,c3))) {
HXLINE( 102)			return ( (int)(::Std_obj::parseInt((HX_("0x",48,2a,00,00) + s.substr(8,null())))) );
            		}
HXLINE( 103)		HX_STACK_DO_THROW((HX_("Unknown resource type: ",3c,fc,2c,c7) + s));
HXDLIN( 103)		return 0;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(RT_obj,fromName,return )


RT_obj::RT_obj()
{
}

bool RT_obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"_n2v") ) { outValue = ( _n2v ); return true; }
		if (HX_FIELD_EQ(inName,"_v2n") ) { outValue = ( _v2n ); return true; }
		if (HX_FIELD_EQ(inName,"init") ) { outValue = init_dyn(); return true; }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"toName") ) { outValue = toName_dyn(); return true; }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"fromName") ) { outValue = fromName_dyn(); return true; }
	}
	return false;
}

bool RT_obj::__SetStatic(const ::String &inName,Dynamic &ioValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"_n2v") ) { _n2v=ioValue.Cast<  ::haxe::ds::StringMap >(); return true; }
		if (HX_FIELD_EQ(inName,"_v2n") ) { _v2n=ioValue.Cast<  ::haxe::ds::IntMap >(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *RT_obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo RT_obj_sStaticStorageInfo[] = {
	{::hx::fsInt,(void *) &RT_obj::NONE,HX_("NONE",b8,da,ca,33)},
	{::hx::fsInt,(void *) &RT_obj::OBJECT,HX_("OBJECT",bf,2a,c2,c7)},
	{::hx::fsInt,(void *) &RT_obj::ROOT,HX_("ROOT",22,b6,6f,36)},
	{::hx::fsInt,(void *) &RT_obj::NODE,HX_("NODE",02,d2,ca,33)},
	{::hx::fsInt,(void *) &RT_obj::INDEX,HX_("INDEX",f2,d2,02,3c)},
	{::hx::fsInt,(void *) &RT_obj::SCRIPT,HX_("SCRIPT",0b,fa,e2,f9)},
	{::hx::fsInt,(void *) &RT_obj::MESH,HX_("MESH",ed,11,1a,33)},
	{::hx::fsInt,(void *) &RT_obj::SKINNEDMESH,HX_("SKINNEDMESH",bd,33,a7,4e)},
	{::hx::fsInt,(void *) &RT_obj::TRANSFORM,HX_("TRANSFORM",4c,9d,eb,40)},
	{::hx::fsInt,(void *) &RT_obj::ANIMATOR,HX_("ANIMATOR",67,0b,78,e2)},
	{::hx::fsInt,(void *) &RT_obj::AVATARREFERENCE,HX_("AVATARREFERENCE",72,80,3e,29)},
	{::hx::fsInt,(void *) &RT_obj::ANIMATION,HX_("ANIMATION",e4,5e,8d,46)},
	{::hx::fsInt,(void *) &RT_obj::MATERIAL,HX_("MATERIAL",a7,ec,2a,4a)},
	{::hx::fsInt,(void *) &RT_obj::MATERIALPOINTER,HX_("MATERIALPOINTER",d6,9a,28,51)},
	{::hx::fsInt,(void *) &RT_obj::TRANSFORMPOINTER,HX_("TRANSFORMPOINTER",d1,78,61,3e)},
	{::hx::fsInt,(void *) &RT_obj::TEXTURE,HX_("TEXTURE",bb,9c,b4,1e)},
	{::hx::fsInt,(void *) &RT_obj::LIGHT,HX_("LIGHT",b6,c8,ea,f2)},
	{::hx::fsInt,(void *) &RT_obj::LIGHTPROBES,HX_("LIGHTPROBES",79,d0,45,bb)},
	{::hx::fsInt,(void *) &RT_obj::INTERNALBUNDLE,HX_("INTERNALBUNDLE",7f,22,cc,56)},
	{::hx::fsInt,(void *) &RT_obj::CAMERA,HX_("CAMERA",a5,f2,0e,6a)},
	{::hx::fsInt,(void *) &RT_obj::COLLIDER,HX_("COLLIDER",34,6f,5b,23)},
	{::hx::fsInt,(void *) &RT_obj::AUDIO,HX_("AUDIO",b6,b0,6e,a5)},
	{::hx::fsInt,(void *) &RT_obj::WEIGHTS,HX_("WEIGHTS",db,ab,d0,ef)},
	{::hx::fsInt,(void *) &RT_obj::PRIMITIVE,HX_("PRIMITIVE",87,f8,b0,22)},
	{::hx::fsInt,(void *) &RT_obj::COLLECTION,HX_("COLLECTION",5e,42,8c,21)},
	{::hx::fsInt,(void *) &RT_obj::POINTERCOLLECTION,HX_("POINTERCOLLECTION",3b,9d,2a,35)},
	{::hx::fsInt,(void *) &RT_obj::CLASS,HX_("CLASS",18,b0,46,c6)},
	{::hx::fsInt,(void *) &RT_obj::GRADIENT,HX_("GRADIENT",f0,c9,c4,83)},
	{::hx::fsInt,(void *) &RT_obj::ANIMATIONCLIP,HX_("ANIMATIONCLIP",b4,d7,73,2f)},
	{::hx::fsInt,(void *) &RT_obj::ANIMATIONCLIPREFERENCE,HX_("ANIMATIONCLIPREFERENCE",77,09,53,df)},
	{::hx::fsInt,(void *) &RT_obj::ANIMATIONLOADER,HX_("ANIMATIONLOADER",f7,95,f7,23)},
	{::hx::fsInt,(void *) &RT_obj::GRIDCLUSTER,HX_("GRIDCLUSTER",d4,e4,30,1b)},
	{::hx::fsObject /*  ::haxe::ds::StringMap */ ,(void *) &RT_obj::_n2v,HX_("_n2v",f3,e8,1e,3f)},
	{::hx::fsObject /*  ::haxe::ds::IntMap */ ,(void *) &RT_obj::_v2n,HX_("_v2n",f3,fa,24,3f)},
	{ ::hx::fsUnknown, 0, null()}
};
#endif

static void RT_obj_sMarkStatics(HX_MARK_PARAMS) {
	HX_MARK_MEMBER_NAME(RT_obj::NONE,"NONE");
	HX_MARK_MEMBER_NAME(RT_obj::OBJECT,"OBJECT");
	HX_MARK_MEMBER_NAME(RT_obj::ROOT,"ROOT");
	HX_MARK_MEMBER_NAME(RT_obj::NODE,"NODE");
	HX_MARK_MEMBER_NAME(RT_obj::INDEX,"INDEX");
	HX_MARK_MEMBER_NAME(RT_obj::SCRIPT,"SCRIPT");
	HX_MARK_MEMBER_NAME(RT_obj::MESH,"MESH");
	HX_MARK_MEMBER_NAME(RT_obj::SKINNEDMESH,"SKINNEDMESH");
	HX_MARK_MEMBER_NAME(RT_obj::TRANSFORM,"TRANSFORM");
	HX_MARK_MEMBER_NAME(RT_obj::ANIMATOR,"ANIMATOR");
	HX_MARK_MEMBER_NAME(RT_obj::AVATARREFERENCE,"AVATARREFERENCE");
	HX_MARK_MEMBER_NAME(RT_obj::ANIMATION,"ANIMATION");
	HX_MARK_MEMBER_NAME(RT_obj::MATERIAL,"MATERIAL");
	HX_MARK_MEMBER_NAME(RT_obj::MATERIALPOINTER,"MATERIALPOINTER");
	HX_MARK_MEMBER_NAME(RT_obj::TRANSFORMPOINTER,"TRANSFORMPOINTER");
	HX_MARK_MEMBER_NAME(RT_obj::TEXTURE,"TEXTURE");
	HX_MARK_MEMBER_NAME(RT_obj::LIGHT,"LIGHT");
	HX_MARK_MEMBER_NAME(RT_obj::LIGHTPROBES,"LIGHTPROBES");
	HX_MARK_MEMBER_NAME(RT_obj::INTERNALBUNDLE,"INTERNALBUNDLE");
	HX_MARK_MEMBER_NAME(RT_obj::CAMERA,"CAMERA");
	HX_MARK_MEMBER_NAME(RT_obj::COLLIDER,"COLLIDER");
	HX_MARK_MEMBER_NAME(RT_obj::AUDIO,"AUDIO");
	HX_MARK_MEMBER_NAME(RT_obj::WEIGHTS,"WEIGHTS");
	HX_MARK_MEMBER_NAME(RT_obj::PRIMITIVE,"PRIMITIVE");
	HX_MARK_MEMBER_NAME(RT_obj::COLLECTION,"COLLECTION");
	HX_MARK_MEMBER_NAME(RT_obj::POINTERCOLLECTION,"POINTERCOLLECTION");
	HX_MARK_MEMBER_NAME(RT_obj::CLASS,"CLASS");
	HX_MARK_MEMBER_NAME(RT_obj::GRADIENT,"GRADIENT");
	HX_MARK_MEMBER_NAME(RT_obj::ANIMATIONCLIP,"ANIMATIONCLIP");
	HX_MARK_MEMBER_NAME(RT_obj::ANIMATIONCLIPREFERENCE,"ANIMATIONCLIPREFERENCE");
	HX_MARK_MEMBER_NAME(RT_obj::ANIMATIONLOADER,"ANIMATIONLOADER");
	HX_MARK_MEMBER_NAME(RT_obj::GRIDCLUSTER,"GRIDCLUSTER");
	HX_MARK_MEMBER_NAME(RT_obj::_n2v,"_n2v");
	HX_MARK_MEMBER_NAME(RT_obj::_v2n,"_v2n");
};

#ifdef HXCPP_VISIT_ALLOCS
static void RT_obj_sVisitStatics(HX_VISIT_PARAMS) {
	HX_VISIT_MEMBER_NAME(RT_obj::NONE,"NONE");
	HX_VISIT_MEMBER_NAME(RT_obj::OBJECT,"OBJECT");
	HX_VISIT_MEMBER_NAME(RT_obj::ROOT,"ROOT");
	HX_VISIT_MEMBER_NAME(RT_obj::NODE,"NODE");
	HX_VISIT_MEMBER_NAME(RT_obj::INDEX,"INDEX");
	HX_VISIT_MEMBER_NAME(RT_obj::SCRIPT,"SCRIPT");
	HX_VISIT_MEMBER_NAME(RT_obj::MESH,"MESH");
	HX_VISIT_MEMBER_NAME(RT_obj::SKINNEDMESH,"SKINNEDMESH");
	HX_VISIT_MEMBER_NAME(RT_obj::TRANSFORM,"TRANSFORM");
	HX_VISIT_MEMBER_NAME(RT_obj::ANIMATOR,"ANIMATOR");
	HX_VISIT_MEMBER_NAME(RT_obj::AVATARREFERENCE,"AVATARREFERENCE");
	HX_VISIT_MEMBER_NAME(RT_obj::ANIMATION,"ANIMATION");
	HX_VISIT_MEMBER_NAME(RT_obj::MATERIAL,"MATERIAL");
	HX_VISIT_MEMBER_NAME(RT_obj::MATERIALPOINTER,"MATERIALPOINTER");
	HX_VISIT_MEMBER_NAME(RT_obj::TRANSFORMPOINTER,"TRANSFORMPOINTER");
	HX_VISIT_MEMBER_NAME(RT_obj::TEXTURE,"TEXTURE");
	HX_VISIT_MEMBER_NAME(RT_obj::LIGHT,"LIGHT");
	HX_VISIT_MEMBER_NAME(RT_obj::LIGHTPROBES,"LIGHTPROBES");
	HX_VISIT_MEMBER_NAME(RT_obj::INTERNALBUNDLE,"INTERNALBUNDLE");
	HX_VISIT_MEMBER_NAME(RT_obj::CAMERA,"CAMERA");
	HX_VISIT_MEMBER_NAME(RT_obj::COLLIDER,"COLLIDER");
	HX_VISIT_MEMBER_NAME(RT_obj::AUDIO,"AUDIO");
	HX_VISIT_MEMBER_NAME(RT_obj::WEIGHTS,"WEIGHTS");
	HX_VISIT_MEMBER_NAME(RT_obj::PRIMITIVE,"PRIMITIVE");
	HX_VISIT_MEMBER_NAME(RT_obj::COLLECTION,"COLLECTION");
	HX_VISIT_MEMBER_NAME(RT_obj::POINTERCOLLECTION,"POINTERCOLLECTION");
	HX_VISIT_MEMBER_NAME(RT_obj::CLASS,"CLASS");
	HX_VISIT_MEMBER_NAME(RT_obj::GRADIENT,"GRADIENT");
	HX_VISIT_MEMBER_NAME(RT_obj::ANIMATIONCLIP,"ANIMATIONCLIP");
	HX_VISIT_MEMBER_NAME(RT_obj::ANIMATIONCLIPREFERENCE,"ANIMATIONCLIPREFERENCE");
	HX_VISIT_MEMBER_NAME(RT_obj::ANIMATIONLOADER,"ANIMATIONLOADER");
	HX_VISIT_MEMBER_NAME(RT_obj::GRIDCLUSTER,"GRIDCLUSTER");
	HX_VISIT_MEMBER_NAME(RT_obj::_n2v,"_n2v");
	HX_VISIT_MEMBER_NAME(RT_obj::_v2n,"_v2n");
};

#endif

::hx::Class RT_obj::__mClass;

static ::String RT_obj_sStaticFields[] = {
	HX_("NONE",b8,da,ca,33),
	HX_("OBJECT",bf,2a,c2,c7),
	HX_("ROOT",22,b6,6f,36),
	HX_("NODE",02,d2,ca,33),
	HX_("INDEX",f2,d2,02,3c),
	HX_("SCRIPT",0b,fa,e2,f9),
	HX_("MESH",ed,11,1a,33),
	HX_("SKINNEDMESH",bd,33,a7,4e),
	HX_("TRANSFORM",4c,9d,eb,40),
	HX_("ANIMATOR",67,0b,78,e2),
	HX_("AVATARREFERENCE",72,80,3e,29),
	HX_("ANIMATION",e4,5e,8d,46),
	HX_("MATERIAL",a7,ec,2a,4a),
	HX_("MATERIALPOINTER",d6,9a,28,51),
	HX_("TRANSFORMPOINTER",d1,78,61,3e),
	HX_("TEXTURE",bb,9c,b4,1e),
	HX_("LIGHT",b6,c8,ea,f2),
	HX_("LIGHTPROBES",79,d0,45,bb),
	HX_("INTERNALBUNDLE",7f,22,cc,56),
	HX_("CAMERA",a5,f2,0e,6a),
	HX_("COLLIDER",34,6f,5b,23),
	HX_("AUDIO",b6,b0,6e,a5),
	HX_("WEIGHTS",db,ab,d0,ef),
	HX_("PRIMITIVE",87,f8,b0,22),
	HX_("COLLECTION",5e,42,8c,21),
	HX_("POINTERCOLLECTION",3b,9d,2a,35),
	HX_("CLASS",18,b0,46,c6),
	HX_("GRADIENT",f0,c9,c4,83),
	HX_("ANIMATIONCLIP",b4,d7,73,2f),
	HX_("ANIMATIONCLIPREFERENCE",77,09,53,df),
	HX_("ANIMATIONLOADER",f7,95,f7,23),
	HX_("GRIDCLUSTER",d4,e4,30,1b),
	HX_("_n2v",f3,e8,1e,3f),
	HX_("_v2n",f3,fa,24,3f),
	HX_("init",10,3b,bb,45),
	HX_("toName",66,dd,b8,7e),
	HX_("fromName",d5,40,cb,a6),
	::String(null())
};

void RT_obj::__register()
{
	RT_obj _hx_dummy;
	RT_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("RT",c2,47,00,00);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &RT_obj::__GetStatic;
	__mClass->mSetStaticField = &RT_obj::__SetStatic;
	__mClass->mMarkFunc = RT_obj_sMarkStatics;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(RT_obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< RT_obj >;
#ifdef HXCPP_VISIT_ALLOCS
	__mClass->mVisitFunc = RT_obj_sVisitStatics;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = RT_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = RT_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

void RT_obj::__boot()
{
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_12_boot)
HXDLIN(  12)		NONE = 0;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_13_boot)
HXDLIN(  13)		OBJECT = 1;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_14_boot)
HXDLIN(  14)		ROOT = 2;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_15_boot)
HXDLIN(  15)		NODE = 4;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_16_boot)
HXDLIN(  16)		INDEX = 8;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_17_boot)
HXDLIN(  17)		SCRIPT = 16;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_18_boot)
HXDLIN(  18)		MESH = 32;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_19_boot)
HXDLIN(  19)		SKINNEDMESH = 64;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_20_boot)
HXDLIN(  20)		TRANSFORM = 128;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_21_boot)
HXDLIN(  21)		ANIMATOR = 256;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_22_boot)
HXDLIN(  22)		AVATARREFERENCE = 512;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_23_boot)
HXDLIN(  23)		ANIMATION = 1024;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_24_boot)
HXDLIN(  24)		MATERIAL = 2048;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_25_boot)
HXDLIN(  25)		MATERIALPOINTER = 4096;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_26_boot)
HXDLIN(  26)		TRANSFORMPOINTER = 8192;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_27_boot)
HXDLIN(  27)		TEXTURE = 16384;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_28_boot)
HXDLIN(  28)		LIGHT = 32768;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_29_boot)
HXDLIN(  29)		LIGHTPROBES = 65536;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_30_boot)
HXDLIN(  30)		INTERNALBUNDLE = 131072;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_31_boot)
HXDLIN(  31)		CAMERA = 262144;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_32_boot)
HXDLIN(  32)		COLLIDER = 524288;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_33_boot)
HXDLIN(  33)		AUDIO = 1048576;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_34_boot)
HXDLIN(  34)		WEIGHTS = 2097152;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_35_boot)
HXDLIN(  35)		PRIMITIVE = 4194304;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_36_boot)
HXDLIN(  36)		COLLECTION = 8388608;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_37_boot)
HXDLIN(  37)		POINTERCOLLECTION = 16777216;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_38_boot)
HXDLIN(  38)		CLASS = 33554432;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_39_boot)
HXDLIN(  39)		GRADIENT = 67108864;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_40_boot)
HXDLIN(  40)		ANIMATIONCLIP = 134217728;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_42_boot)
HXDLIN(  42)		ANIMATIONCLIPREFERENCE = 268435456;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_43_boot)
HXDLIN(  43)		ANIMATIONLOADER = 536870912;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_44_boot)
HXDLIN(  44)		GRIDCLUSTER = (int)1073741824;
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_46_boot)
HXDLIN(  46)		_n2v = null();
            	}
{
            	HX_STACKFRAME(&_hx_pos_3d74350a37f62501_47_boot)
HXDLIN(  47)		_v2n = null();
            	}
}

