// Generated by Haxe 4.3.7
#ifndef INCLUDED_BinReader
#define INCLUDED_BinReader

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(BinReader)
HX_DECLARE_CLASS2(haxe,io,Bytes)
HX_DECLARE_CLASS2(haxe,io,BytesInput)
HX_DECLARE_CLASS2(haxe,io,Input)



class HXCPP_CLASS_ATTRIBUTES BinReader_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef BinReader_obj OBJ_;
		BinReader_obj();

	public:
		enum { _hx_ClassId = 0x595748a6 };

		void __construct( ::haxe::io::Bytes b);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="BinReader")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"BinReader"); }
		static ::hx::ObjectPtr< BinReader_obj > __new( ::haxe::io::Bytes b);
		static ::hx::ObjectPtr< BinReader_obj > __alloc(::hx::Ctx *_hx_ctx, ::haxe::io::Bytes b);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~BinReader_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("BinReader",4a,01,4d,e7); }

		static ::String hexU32(int v);
		static ::Dynamic hexU32_dyn();

		static int parseHex(::String s);
		static ::Dynamic parseHex_dyn();

		 ::haxe::io::BytesInput bi;
		int readI32();
		::Dynamic readI32_dyn();

		int readU32();
		::Dynamic readU32_dyn();

		bool readBool();
		::Dynamic readBool_dyn();

		 ::haxe::io::Bytes readBytes(int n);
		::Dynamic readBytes_dyn();

		::String readUtf8(int n);
		::Dynamic readUtf8_dyn();

		void skip(int n);
		::Dynamic skip_dyn();

		int pos();
		::Dynamic pos_dyn();

		int remaining();
		::Dynamic remaining_dyn();

		bool eof();
		::Dynamic eof_dyn();

};


#endif /* INCLUDED_BinReader */ 
