// Generated by Haxe 4.3.7
#ifndef INCLUDED_BinWriter
#define INCLUDED_BinWriter

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(BinWriter)
HX_DECLARE_CLASS2(haxe,io,Bytes)
HX_DECLARE_CLASS2(haxe,io,BytesOutput)
HX_DECLARE_CLASS2(haxe,io,Output)



class HXCPP_CLASS_ATTRIBUTES BinWriter_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef BinWriter_obj OBJ_;
		BinWriter_obj();

	public:
		enum { _hx_ClassId = 0x2be4a7fa };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="BinWriter")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"BinWriter"); }
		static ::hx::ObjectPtr< BinWriter_obj > __new();
		static ::hx::ObjectPtr< BinWriter_obj > __alloc(::hx::Ctx *_hx_ctx);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~BinWriter_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("BinWriter",ba,32,a1,68); }

		 ::haxe::io::BytesOutput bo;
		void writeI32(int v);
		::Dynamic writeI32_dyn();

		void writeBool(bool v);
		::Dynamic writeBool_dyn();

		void writeBytes( ::haxe::io::Bytes b);
		::Dynamic writeBytes_dyn();

		void writeUtf8(::String s);
		::Dynamic writeUtf8_dyn();

		int len();
		::Dynamic len_dyn();

		 ::haxe::io::Bytes get();
		::Dynamic get_dyn();

};


#endif /* INCLUDED_BinWriter */ 
