// Generated by Haxe 4.3.7
#ifndef INCLUDED_FS
#define INCLUDED_FS

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(FS)
HX_DECLARE_CLASS2(haxe,io,Bytes)



class HXCPP_CLASS_ATTRIBUTES FS_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef FS_obj OBJ_;
		FS_obj();

	public:
		enum { _hx_ClassId = 0x2682a00d };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="FS")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"FS"); }

		inline static ::hx::ObjectPtr< FS_obj > __new() {
			::hx::ObjectPtr< FS_obj > __this = new FS_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< FS_obj > __alloc(::hx::Ctx *_hx_ctx) {
			FS_obj *__this = (FS_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(FS_obj), false, "FS"));
			*(void **)__this = FS_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~FS_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("FS",4d,3d,00,00); }

		static void mkdirs(::String path);
		static ::Dynamic mkdirs_dyn();

		static void mkdir(::String path);
		static ::Dynamic mkdir_dyn();

		static bool exists(::String path);
		static ::Dynamic exists_dyn();

		static ::Array< ::String > subdirs(::String path);
		static ::Dynamic subdirs_dyn();

		static ::Array< ::String > files(::String path);
		static ::Dynamic files_dyn();

		static ::String join(::String a,::String b);
		static ::Dynamic join_dyn();

		static  ::haxe::io::Bytes readBytes(::String path);
		static ::Dynamic readBytes_dyn();

		static void writeBytes(::String path, ::haxe::io::Bytes b);
		static ::Dynamic writeBytes_dyn();

		static  ::Dynamic readJson(::String path);
		static ::Dynamic readJson_dyn();

		static void writeJson(::String path, ::Dynamic v);
		static ::Dynamic writeJson_dyn();

		static ::String hex8(int v);
		static ::Dynamic hex8_dyn();

		static int unhex8(::String s);
		static ::Dynamic unhex8_dyn();

};


#endif /* INCLUDED_FS */ 
