// Generated by Haxe 4.3.7
#ifndef INCLUDED_MetaDataType
#define INCLUDED_MetaDataType

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(MetaDataType)



class HXCPP_CLASS_ATTRIBUTES MetaDataType_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef MetaDataType_obj OBJ_;
		MetaDataType_obj();

	public:
		enum { _hx_ClassId = 0x2ee5ac2d };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="MetaDataType")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"MetaDataType"); }

		inline static ::hx::ObjectPtr< MetaDataType_obj > __new() {
			::hx::ObjectPtr< MetaDataType_obj > __this = new MetaDataType_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< MetaDataType_obj > __alloc(::hx::Ctx *_hx_ctx) {
			MetaDataType_obj *__this = (MetaDataType_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(MetaDataType_obj), false, "MetaDataType"));
			*(void **)__this = MetaDataType_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~MetaDataType_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("MetaDataType",09,f2,b9,13); }

		static void __boot();
		static int UNKNOWN;
		static int JSON;
		static int BINARY;
		static int PROTOBUF;
		static ::String name(int v);
		static ::Dynamic name_dyn();

		static ::String ext(int v);
		static ::Dynamic ext_dyn();

};


#endif /* INCLUDED_MetaDataType */ 
