// Generated by Haxe 4.3.7
#ifndef INCLUDED_PCFBlockTypes
#define INCLUDED_PCFBlockTypes

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(PCFBlockTypes)



class HXCPP_CLASS_ATTRIBUTES PCFBlockTypes_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef PCFBlockTypes_obj OBJ_;
		PCFBlockTypes_obj();

	public:
		enum { _hx_ClassId = 0x033969ff };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="PCFBlockTypes")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"PCFBlockTypes"); }

		inline static ::hx::ObjectPtr< PCFBlockTypes_obj > __new() {
			::hx::ObjectPtr< PCFBlockTypes_obj > __this = new PCFBlockTypes_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< PCFBlockTypes_obj > __alloc(::hx::Ctx *_hx_ctx) {
			PCFBlockTypes_obj *__this = (PCFBlockTypes_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(PCFBlockTypes_obj), false, "PCFBlockTypes"));
			*(void **)__this = PCFBlockTypes_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~PCFBlockTypes_obj();

		HX_DO_RTTI_ALL;
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("PCFBlockTypes",bf,54,f2,26); }

		static void __boot();
		static int RESOURCE;
		static int INDEX;
		static int NODE;
};


#endif /* INCLUDED_PCFBlockTypes */ 
