// Generated by Haxe 4.3.7
#ifndef INCLUDED_Unpacker
#define INCLUDED_Unpacker

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(BinReader)
HX_DECLARE_CLASS0(Unpacker)
HX_DECLARE_CLASS1(haxe,IMap)
HX_DECLARE_CLASS2(haxe,ds,IntMap)
HX_DECLARE_CLASS2(haxe,io,Bytes)



class HXCPP_CLASS_ATTRIBUTES Unpacker_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Unpacker_obj OBJ_;
		Unpacker_obj();

	public:
		enum { _hx_ClassId = 0x1b22357f };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="Unpacker")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"Unpacker"); }

		inline static ::hx::ObjectPtr< Unpacker_obj > __new() {
			::hx::ObjectPtr< Unpacker_obj > __this = new Unpacker_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< Unpacker_obj > __alloc(::hx::Ctx *_hx_ctx) {
			Unpacker_obj *__this = (Unpacker_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Unpacker_obj), false, "Unpacker"));
			*(void **)__this = Unpacker_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Unpacker_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Unpacker",bf,42,91,bf); }

		static void run(::String pcfPath,::String outDir);
		static ::Dynamic run_dyn();

		static void writeHeader(::String outDir,int version,int fileLength,int fileType);
		static ::Dynamic writeHeader_dyn();

		static  ::Dynamic parseNodeBlock( ::haxe::io::Bytes bytes);
		static ::Dynamic parseNodeBlock_dyn();

		static  ::Dynamic readNodeRec( ::BinReader r);
		static ::Dynamic readNodeRec_dyn();

		static  ::Dynamic nodeRecToJson( ::Dynamic n);
		static ::Dynamic nodeRecToJson_dyn();

		static  ::Dynamic parseResBlock(int rt, ::haxe::io::Bytes bytes);
		static ::Dynamic parseResBlock_dyn();

		static void writeResBlock(::String resRoot, ::Dynamic rb);
		static ::Dynamic writeResBlock_dyn();

		static void writeAsset(::String typeDir, ::Dynamic a,int rt,int order);
		static ::Dynamic writeAsset_dyn();

		static  ::Dynamic vec3bits( ::haxe::io::Bytes b,int off);
		static ::Dynamic vec3bits_dyn();

		static  ::Dynamic rgba_bits( ::haxe::io::Bytes b,int off);
		static ::Dynamic rgba_bits_dyn();

		static  ::Dynamic floatField( ::haxe::io::Bytes b,int idx);
		static ::Dynamic floatField_dyn();

		static ::Array< Float > readFloats( ::haxe::io::Bytes b,int n);
		static ::Dynamic readFloats_dyn();

		static  ::Dynamic vec3(::Array< Float > f,int o);
		static ::Dynamic vec3_dyn();

		static  ::Dynamic rgba(::Array< Float > f,int o);
		static ::Dynamic rgba_dyn();

		static Float roundF(Float f);
		static ::Dynamic roundF_dyn();

		static void writeJsonMeta(::String assetDir,::String jsonName, ::haxe::io::Bytes meta);
		static ::Dynamic writeJsonMeta_dyn();

		static void extractMesh(::String assetDir, ::haxe::io::Bytes data,bool readSkinning, ::Dynamic matID,::cpp::VirtualArray boneNames);
		static ::Dynamic extractMesh_dyn();

		static int readU16( ::BinReader r);
		static ::Dynamic readU16_dyn();

		static Float readF32( ::BinReader r);
		static ::Dynamic readF32_dyn();

		static int getU16( ::haxe::io::Bytes b,int off);
		static ::Dynamic getU16_dyn();

		static ::String f6(Float v);
		static ::Dynamic f6_dyn();

		static  ::Dynamic decodeMaterial( ::haxe::io::Bytes b);
		static ::Dynamic decodeMaterial_dyn();

		static  ::Dynamic decodeAnimationClip( ::haxe::io::Bytes b);
		static ::Dynamic decodeAnimationClip_dyn();

		static ::String animChannelName(int v);
		static ::Dynamic animChannelName_dyn();

		static ::Array< ::Dynamic> scanProtobufMulti( ::haxe::io::Bytes b,int targetField);
		static ::Dynamic scanProtobufMulti_dyn();

		static  ::haxe::ds::IntMap scanProtobufF32( ::haxe::io::Bytes b);
		static ::Dynamic scanProtobufF32_dyn();

		static  ::Dynamic decodeSerializedFieldData( ::haxe::io::Bytes b);
		static ::Dynamic decodeSerializedFieldData_dyn();

		static  ::Dynamic decodeSerializedCollectionData( ::haxe::io::Bytes b);
		static ::Dynamic decodeSerializedCollectionData_dyn();

		static ::String assemblyName(int t);
		static ::Dynamic assemblyName_dyn();

		static  ::Dynamic decodeWeights( ::haxe::io::Bytes data);
		static ::Dynamic decodeWeights_dyn();

		static ::String textureFormatName(int fmt);
		static ::Dynamic textureFormatName_dyn();

		static  ::Dynamic parseJsonMeta( ::haxe::io::Bytes b);
		static ::Dynamic parseJsonMeta_dyn();

		static  ::Dynamic decodePrimitive( ::haxe::io::Bytes metaBytes, ::haxe::io::Bytes dataBytes);
		static ::Dynamic decodePrimitive_dyn();

		static  ::haxe::ds::IntMap scanProtobuf( ::haxe::io::Bytes b);
		static ::Dynamic scanProtobuf_dyn();

		static  ::Dynamic readVarint( ::haxe::io::Bytes b,int p);
		static ::Dynamic readVarint_dyn();

		static void die(::String msg);
		static ::Dynamic die_dyn();

};


#endif /* INCLUDED_Unpacker */ 
