// Generated by Haxe 4.3.7
#ifndef INCLUDED_Packer
#define INCLUDED_Packer

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(BinWriter)
HX_DECLARE_CLASS0(Packer)
HX_DECLARE_CLASS2(haxe,io,Bytes)



class HXCPP_CLASS_ATTRIBUTES Packer_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Packer_obj OBJ_;
		Packer_obj();

	public:
		enum { _hx_ClassId = 0x79778e66 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="Packer")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"Packer"); }

		inline static ::hx::ObjectPtr< Packer_obj > __new() {
			::hx::ObjectPtr< Packer_obj > __this = new Packer_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< Packer_obj > __alloc(::hx::Ctx *_hx_ctx) {
			Packer_obj *__this = (Packer_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Packer_obj), false, "Packer"));
			*(void **)__this = Packer_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Packer_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Packer",a6,cb,2c,18); }

		static void run(::String inDir,::String pcfPath);
		static ::Dynamic run_dyn();

		static  ::haxe::io::Bytes buildIndexBlock(::Array< ::Dynamic> entries);
		static ::Dynamic buildIndexBlock_dyn();

		static  ::Dynamic jsonToNodeRec( ::Dynamic j);
		static ::Dynamic jsonToNodeRec_dyn();

		static  ::haxe::io::Bytes serializeNodePayload( ::Dynamic root);
		static ::Dynamic serializeNodePayload_dyn();

		static void writeNodeRec( ::BinWriter w, ::Dynamic n);
		static ::Dynamic writeNodeRec_dyn();

		static  ::haxe::io::Bytes serializeResPayload(::String typeDir,int rt);
		static ::Dynamic serializeResPayload_dyn();

		static void serializeAsset( ::BinWriter w,::String assetDir,int rt);
		static ::Dynamic serializeAsset_dyn();

		static  ::haxe::io::Bytes readMeta(::String d,int rt,int mdType);
		static ::Dynamic readMeta_dyn();

		static  ::haxe::io::Bytes readData(::String d,int rt);
		static ::Dynamic readData_dyn();

		static  ::haxe::io::Bytes encodeFloatData(::String d,::String jsonFile,::Array< ::String > vecKeys);
		static ::Dynamic encodeFloatData_dyn();

		static  ::haxe::io::Bytes encodeCameraData(::String d);
		static ::Dynamic encodeCameraData_dyn();

		static  ::haxe::io::Bytes encodeLightData(::String d);
		static ::Dynamic encodeLightData_dyn();

		static  ::haxe::io::Bytes encodeMeshFromObj(::String d,bool isSkinned);
		static ::Dynamic encodeMeshFromObj_dyn();

		static void writeU16( ::BinWriter w,int v);
		static ::Dynamic writeU16_dyn();

		static int clampByte(Float v);
		static ::Dynamic clampByte_dyn();

		static void writeVec3Array16bit( ::BinWriter w,::Array< ::Dynamic> arr);
		static ::Dynamic writeVec3Array16bit_dyn();

		static void writeVec2Array16bit( ::BinWriter w,::Array< ::Dynamic> arr);
		static ::Dynamic writeVec2Array16bit_dyn();

		static int clampF(Float v);
		static ::Dynamic clampF_dyn();

		static int floatBits( ::Dynamic obj,::String valKey,::String bitsKey);
		static ::Dynamic floatBits_dyn();

		static int floatFieldBits( ::Dynamic obj);
		static ::Dynamic floatFieldBits_dyn();

		static  ::haxe::io::Bytes encodeMaterial(::String d);
		static ::Dynamic encodeMaterial_dyn();

		static  ::haxe::io::Bytes encodePrimitiveMeta(::String d);
		static ::Dynamic encodePrimitiveMeta_dyn();

		static  ::haxe::io::Bytes encodePrimitiveData(::String d);
		static ::Dynamic encodePrimitiveData_dyn();

		static  ::haxe::io::Bytes encodeAnimationClip(::String d);
		static ::Dynamic encodeAnimationClip_dyn();

		static  ::haxe::io::Bytes encodeWeightsData(::String d);
		static ::Dynamic encodeWeightsData_dyn();

		static void pbWriteFixed32( ::BinWriter w,int fieldNo,int bits);
		static ::Dynamic pbWriteFixed32_dyn();

		static  ::haxe::io::Bytes encodeSerializedFieldData(::String d,::String infoFile);
		static ::Dynamic encodeSerializedFieldData_dyn();

		static  ::haxe::io::Bytes encodeSerializedCollectionData(::String d,::String infoFile);
		static ::Dynamic encodeSerializedCollectionData_dyn();

		static void pbWriteVarint( ::BinWriter w,int v);
		static ::Dynamic pbWriteVarint_dyn();

		static void pbWriteVarintRaw( ::BinWriter w,int v);
		static ::Dynamic pbWriteVarintRaw_dyn();

		static void pbWriteLenDelim( ::BinWriter w,int fieldNo, ::haxe::io::Bytes data);
		static ::Dynamic pbWriteLenDelim_dyn();

		static Float fF( ::Dynamic o,::String k);
		static ::Dynamic fF_dyn();

		static  ::haxe::io::Bytes compactJsonBytes(::String d,::String name);
		static ::Dynamic compactJsonBytes_dyn();

		static  ::haxe::io::Bytes readMetaRaw(::String d,::String jsonName);
		static ::Dynamic readMetaRaw_dyn();

		static  ::haxe::io::Bytes tryRead(::String d,::String name);
		static ::Dynamic tryRead_dyn();

		static int iF( ::Dynamic o,::String k);
		static ::Dynamic iF_dyn();

		static ::String sF( ::Dynamic o,::String k);
		static ::Dynamic sF_dyn();

		static bool bF( ::Dynamic o,::String k);
		static ::Dynamic bF_dyn();

		static void die(::String msg);
		static ::Dynamic die_dyn();

};


#endif /* INCLUDED_Packer */ 
