// Generated by Haxe 4.3.7
#ifndef INCLUDED_PCFfileType
#define INCLUDED_PCFfileType

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(PCFfileType)



class HXCPP_CLASS_ATTRIBUTES PCFfileType_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef PCFfileType_obj OBJ_;
		PCFfileType_obj();

	public:
		enum { _hx_ClassId = 0x6049ba89 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="PCFfileType")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"PCFfileType"); }

		inline static ::hx::ObjectPtr< PCFfileType_obj > __new() {
			::hx::ObjectPtr< PCFfileType_obj > __this = new PCFfileType_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< PCFfileType_obj > __alloc(::hx::Ctx *_hx_ctx) {
			PCFfileType_obj *__this = (PCFfileType_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(PCFfileType_obj), false, "PCFfileType"));
			*(void **)__this = PCFfileType_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~PCFfileType_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("PCFfileType",49,75,4e,ad); }

		static ::String name(int v);
		static ::Dynamic name_dyn();

};


#endif /* INCLUDED_PCFfileType */ 
