// Generated by Haxe 4.3.7
#ifndef INCLUDED_RT
#define INCLUDED_RT

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(RT)
HX_DECLARE_CLASS1(haxe,IMap)
HX_DECLARE_CLASS2(haxe,ds,IntMap)
HX_DECLARE_CLASS2(haxe,ds,StringMap)



class HXCPP_CLASS_ATTRIBUTES RT_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef RT_obj OBJ_;
		RT_obj();

	public:
		enum { _hx_ClassId = 0x2682aa82 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="RT")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"RT"); }

		inline static ::hx::ObjectPtr< RT_obj > __new() {
			::hx::ObjectPtr< RT_obj > __this = new RT_obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< RT_obj > __alloc(::hx::Ctx *_hx_ctx) {
			RT_obj *__this = (RT_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(RT_obj), false, "RT"));
			*(void **)__this = RT_obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~RT_obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, Dynamic &ioValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("RT",c2,47,00,00); }

		static void __boot();
		static int NONE;
		static int OBJECT;
		static int ROOT;
		static int NODE;
		static int INDEX;
		static int SCRIPT;
		static int MESH;
		static int SKINNEDMESH;
		static int TRANSFORM;
		static int ANIMATOR;
		static int AVATARREFERENCE;
		static int ANIMATION;
		static int MATERIAL;
		static int MATERIALPOINTER;
		static int TRANSFORMPOINTER;
		static int TEXTURE;
		static int LIGHT;
		static int LIGHTPROBES;
		static int INTERNALBUNDLE;
		static int CAMERA;
		static int COLLIDER;
		static int AUDIO;
		static int WEIGHTS;
		static int PRIMITIVE;
		static int COLLECTION;
		static int POINTERCOLLECTION;
		static int CLASS;
		static int GRADIENT;
		static int ANIMATIONCLIP;
		static int ANIMATIONCLIPREFERENCE;
		static int ANIMATIONLOADER;
		static int GRIDCLUSTER;
		static  ::haxe::ds::StringMap _n2v;
		static  ::haxe::ds::IntMap _v2n;
		static void init();
		static ::Dynamic init_dyn();

		static ::String toName(int v);
		static ::Dynamic toName_dyn();

		static int fromName(::String s);
		static ::Dynamic fromName_dyn();

};


#endif /* INCLUDED_RT */ 
